
package org.okj.commons.soap.client.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BilldocumentReadService", targetNamespace = "http://ericsson.com/services/ws_CIL_5")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BilldocumentReadService {


    /**
     * 
     * @param billdocumentReadRequest
     * @return
     *     returns com.ericsson.services.ws_cil_5.billdocumentread.BilldocumentReadResponse
     */
    @WebMethod
    @WebResult(name = "billdocumentReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/billdocumentread", partName = "billdocumentReadResponse")
    public BilldocumentReadResponse billdocumentRead(
        @WebParam(name = "billdocumentReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/billdocumentread", partName = "billdocumentReadRequest")
        BilldocumentReadRequest billdocumentReadRequest);

}
